
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '7FC74EF495133D109EF3475AC2566662'
    
_lr_action_items = {'DEDENT':([14,16,17,19,21,25,27,32,34,35,36,37,40,41,43,46,],[-20,-20,-6,23,-8,-20,-20,37,-10,-20,-9,-5,43,-12,-7,-11,]),'LID':([28,29,30,31,33,],[-13,-14,-15,-16,38,]),'NL':([4,12,18,24,38,39,44,45,],[9,13,22,26,-17,41,46,-18,]),'CID':([2,6,],[4,10,]),'INT':([25,27,35,41,46,],[28,28,28,-12,-11,]),'ACTUATORS':([14,],[15,]),'FLOAT':([25,27,35,41,46,],[29,29,29,-12,-11,]),'POS':([25,27,35,41,46,],[30,30,30,-12,-11,]),'MODULE':([3,7,9,23,],[6,6,-19,-4,]),'ASGN':([38,39,],[-17,42,]),'BOOL':([25,27,35,41,46,],[31,31,31,-12,-11,]),'COLON':([10,15,20,],[12,18,24,]),'AGENT':([0,],[2,]),'INUM':([42,],[45,]),'INDENT':([13,22,26,],[14,25,35,]),'SENSORS':([14,16,17,37,],[-20,20,-6,-5,]),'$end':([1,3,5,7,8,9,11,23,],[0,-20,-1,-20,-3,-19,-2,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'decl':([25,27,35,],[27,27,27,]),'exp':([42,],[44,]),'sdecls':([16,],[19,]),'adecls':([14,],[16,]),'pgm':([0,],[1,]),'modules':([3,7,],[5,11,]),'module':([3,7,],[7,7,]),'agnt':([0,],[3,]),'varname':([33,],[39,]),'decls':([25,27,35,],[32,36,40,]),'type':([25,27,35,],[33,33,33,]),'empty':([3,7,14,16,25,27,35,],[8,8,17,21,34,34,34,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> pgm","S'",1,None,None,None),
  ('pgm -> agnt modules','pgm',2,'p_pgm','kparser.py',26),
  ('modules -> module modules','modules',2,'p_modules','kparser.py',30),
  ('modules -> empty','modules',1,'p_modules','kparser.py',31),
  ('module -> MODULE CID COLON NL INDENT adecls sdecls DEDENT','module',8,'p_module','kparser.py',41),
  ('adecls -> ACTUATORS COLON NL INDENT decls DEDENT','adecls',6,'p_adecls','kparser.py',46),
  ('adecls -> empty','adecls',1,'p_adecls','kparser.py',47),
  ('sdecls -> SENSORS COLON NL INDENT decls DEDENT','sdecls',6,'p_sdecls','kparser.py',55),
  ('sdecls -> empty','sdecls',1,'p_sdecls','kparser.py',56),
  ('decls -> decl decls','decls',2,'p_decls','kparser.py',64),
  ('decls -> empty','decls',1,'p_decls','kparser.py',65),
  ('decl -> type varname ASGN exp NL','decl',5,'p_decl','kparser.py',75),
  ('decl -> type varname NL','decl',3,'p_decl','kparser.py',76),
  ('type -> INT','type',1,'p_type','kparser.py',84),
  ('type -> FLOAT','type',1,'p_type','kparser.py',85),
  ('type -> POS','type',1,'p_type','kparser.py',86),
  ('type -> BOOL','type',1,'p_type','kparser.py',87),
  ('varname -> LID','varname',1,'p_varname','kparser.py',92),
  ('exp -> INUM','exp',1,'p_exp','kparser.py',97),
  ('agnt -> AGENT CID NL','agnt',3,'p_agnt','kparser.py',102),
  ('empty -> <empty>','empty',0,'p_empty','kparser.py',106),
]
